// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StonkBot.Data;

#nullable disable

namespace StonkBot.Migrations
{
    [DbContext(typeof(StonkBotDbContext))]
    [Migration("20230321183436_FixAuthTokenEntity")]
    partial class FixAuthTokenEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("StonkBot.Data.Entities.AuthToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("access_token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("expires_in")
                        .HasColumnType("INTEGER");

                    b.Property<string>("refresh_token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("refresh_token_expires_in")
                        .HasColumnType("INTEGER");

                    b.Property<string>("scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("tokenCreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("token_type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("access_token");

                    b.ToTable("AuthTokens");
                });

            modelBuilder.Entity("StonkBot.Data.Entities.CalculatedFields", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("AboveUpperShadow")
                        .HasColumnType("TEXT");

                    b.Property<string>("FHTargetDay")
                        .HasColumnType("TEXT");

                    b.Property<string>("FiveDayStable")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromYesterday")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFHTarget")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("UpToday")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("UpperShadow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VolumeAlert")
                        .HasColumnType("TEXT");

                    b.Property<string>("VolumeAlert2")
                        .HasColumnType("TEXT");

                    b.HasKey("Symbol", "Date");

                    b.HasIndex("Symbol", "Date");

                    b.ToTable("CalculatedFields");
                });

            modelBuilder.Entity("StonkBot.Data.Entities.Candle", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<decimal>("Close")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("High")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Low")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Open")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Volume")
                        .HasColumnType("TEXT");

                    b.HasKey("Symbol", "DateTime");

                    b.HasIndex("Symbol", "DateTime");

                    b.ToTable("Candles");
                });

            modelBuilder.Entity("StonkBot.Data.Entities.DiscordMessageRecord", b =>
                {
                    b.Property<ulong>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId");

                    b.HasIndex("MessageId");

                    b.ToTable("DiscordMessageRecords");
                });

            modelBuilder.Entity("StonkBot.Data.Entities.EarningsReport", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodEnding")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Symbol", "Date");

                    b.HasIndex("Symbol", "Date");

                    b.ToTable("EarningsReports");
                });

            modelBuilder.Entity("StonkBot.Data.Entities.HistoricalData", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<DateTime?>("CalculatedFieldsDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CalculatedFieldsSymbol")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Close")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("High")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Low")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Open")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Volume")
                        .HasColumnType("TEXT");

                    b.HasKey("Symbol", "Date");

                    b.HasIndex("CalculatedFieldsSymbol", "CalculatedFieldsDate");

                    b.HasIndex("Symbol", "Date");

                    b.ToTable("HistoricalData");
                });

            modelBuilder.Entity("StonkBot.Data.Entities.IndustryInfo", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Industry")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sector")
                        .HasColumnType("TEXT");

                    b.HasKey("Symbol");

                    b.HasIndex("Symbol");

                    b.ToTable("IndustryInfo");
                });

            modelBuilder.Entity("StonkBot.Data.Entities.IpoListing", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Close")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("DiscordMessageRecordMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpectedListingDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("High")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Low")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfferAmmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfferingEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfferingPrice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Open")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScrapeDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Volume")
                        .HasColumnType("TEXT");

                    b.HasKey("Symbol");

                    b.HasIndex("DiscordMessageRecordMessageId");

                    b.HasIndex("Symbol");

                    b.ToTable("IpoListings");
                });

            modelBuilder.Entity("StonkBot.Data.Entities.HistoricalData", b =>
                {
                    b.HasOne("StonkBot.Data.Entities.IndustryInfo", "IndustryInfo")
                        .WithMany()
                        .HasForeignKey("Symbol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StonkBot.Data.Entities.CalculatedFields", "CalculatedFields")
                        .WithMany()
                        .HasForeignKey("CalculatedFieldsSymbol", "CalculatedFieldsDate");

                    b.Navigation("CalculatedFields");

                    b.Navigation("IndustryInfo");
                });

            modelBuilder.Entity("StonkBot.Data.Entities.IpoListing", b =>
                {
                    b.HasOne("StonkBot.Data.Entities.DiscordMessageRecord", "DiscordMessageRecord")
                        .WithMany()
                        .HasForeignKey("DiscordMessageRecordMessageId");

                    b.Navigation("DiscordMessageRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
